all:
	$(MAKE) -C lt
	$(MAKE) -C gt
	$(MAKE) -C slt
	$(MAKE) -C sgt
	$(MAKE) -C eq
	$(MAKE) -C iszero
	$(MAKE) -C and
	$(MAKE) -C or
	$(MAKE) -C xor
	$(MAKE) -C not
	$(MAKE) -C byte
	$(MAKE) -C add
	$(MAKE) -C sub
	$(MAKE) -C mul
	$(MAKE) -C div
	$(MAKE) -C mod
	$(MAKE) -C smod
	$(MAKE) -C addmod
	$(MAKE) -C mulmod
	$(MAKE) -C exp
	$(MAKE) -C signextend

run:
	$(MAKE) -C lt run
	$(MAKE) -C gt run
	$(MAKE) -C slt run
	$(MAKE) -C sgt run
	$(MAKE) -C eq run
	$(MAKE) -C iszero run
	$(MAKE) -C and run
	$(MAKE) -C or run
	$(MAKE) -C xor run
	$(MAKE) -C not run
	$(MAKE) -C byte run
	$(MAKE) -C add run
	$(MAKE) -C sub run
	$(MAKE) -C mul run
	$(MAKE) -C div run
	$(MAKE) -C mod run
	$(MAKE) -C smod run
	$(MAKE) -C addmod run
	$(MAKE) -C mulmod run
	$(MAKE) -C exp run
	$(MAKE) -C signextend run

clean:
	$(MAKE) -C lt clean
	$(MAKE) -C gt clean
	$(MAKE) -C slt clean
	$(MAKE) -C sgt clean
	$(MAKE) -C eq clean
	$(MAKE) -C iszero clean
	$(MAKE) -C and clean
	$(MAKE) -C or clean
	$(MAKE) -C xor clean
	$(MAKE) -C not clean
	$(MAKE) -C byte clean
	$(MAKE) -C add clean
	$(MAKE) -C sub clean
	$(MAKE) -C mul clean
	$(MAKE) -C div clean
	$(MAKE) -C mod clean
	$(MAKE) -C smod clean
	$(MAKE) -C addmod clean
	$(MAKE) -C mulmod clean
	$(MAKE) -C exp clean
	$(MAKE) -C signextend clean
