#!/bin/sh

check_success() {
   if [ $? -ne 0 ]
   then
      echo Step failed
      exit 1
   fi
}

./configure-tlm
make clean
make
check_success
make tlmu
check_success
sudo make install-tlmu DESTDIR=/usr
