#!/bin/sh

./configure --target-list=arm-softmmu,ppdl-softmmu --extra-cflags="-fPIC -D TLM" --enable-debug --disable-werror --disable-pie --disable-curses --disable-sdl --disable-vnc --disable-xen --disable-kvm
